name: deploy-backend

on:
  push:
    branches: [ "main", "feat/**" ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/event-backend
  APP_DEPLOYMENT: backend-deployment
  K8S_NAMESPACE: ${{ secrets.KUBE_NAMESPACE }}

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # ให้สิทธิ์ push GHCR

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      # login GHCR ด้วย GitHub token
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build & Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Setup kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          kubectl version --client=true
          kubectl config get-contexts

      - name: Ensure namespace exists
        run: kubectl create ns "$K8S_NAMESPACE" || true

      - name: Apply manifests
        run: kubectl -n "$K8S_NAMESPACE" apply -f k8s/

      - name: Set image to current commit
        run: |
          kubectl -n "$K8S_NAMESPACE" set image deployment/${{ env.APP_DEPLOYMENT }} \
            backend=${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Wait for rollout
        run: kubectl -n "$K8S_NAMESPACE" rollout status deployment/${{ env.APP_DEPLOYMENT }} --timeout=180s
